version: "3.8"

services:
  db:
    image: postgres
    container_name: pavas_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: pavasdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
